service: blog

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:174718084238:table/BlogTable"

functions:
  createArticle:
    handler: articles/create.handler
    events:
      - http:
          path: articles
          method: post
  getArticle:
    handler: articles/get.handler
    events:
      - http:
          path: articles
          method: get
  updateArticle:
    handler: articles/put.handler
    events:
      - http:
          path: articles
          method: put
  deleteArticle:
    handler: articles/delete.handler
    events:
      - http:
          path: articles
          method: delete        

# Dynamo configuration
resources:
  Resources:
    BlogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BlogTable
        AttributeDefinitions: 
         - AttributeName: article_id
           AttributeType: S
        KeySchema:
         - AttributeName: article_id
           KeyType: HASH
        ProvisionedThroughput:
           ReadCapacityUnits: 1
           WriteCapacityUnits: 1
